#!/usr/bin/env bash
# Runs ONLY on workers. Joins the cluster using the command generated by master.sh
set -euo pipefail

JOIN_FILE="/vagrant/join-command.sh"

if grep -q "kubelet-client-current.pem" /var/lib/kubelet/pki/kubelet-client-current.pem 2>/dev/null; then
  echo "==> [worker] Already joined, skipping"
  exit 0
fi

echo "==> [worker] Waiting for master to publish join command..."
for i in $(seq 1 60); do
  if [ -s "$JOIN_FILE" ]; then
    echo "==> [worker] Join command found"
    break
  fi
  echo "    ...still waiting ($i/60)"
  sleep 5
done

if [ ! -s "$JOIN_FILE" ]; then
  echo "!! [worker] Timed out waiting for $JOIN_FILE. Is the master provisioned yet?"
  exit 1
fi

echo "==> [worker] Joining cluster"
bash "$JOIN_FILE"

echo "==> [worker] Done on $(hostname)"
